export type AppTheme = {
  id: string;
  label: string;
  type: "dark" | "light";
  colors: Record<string, string>;
};

export const APP_THEMES: AppTheme[] = [
  {
    id: "one-dark-pro",
    label: "One Dark Pro",
    type: "dark",
    colors: {
      "--background": "#282C34",
      "--foreground": "#ABB2BF",
      "--card": "#2C323C",
      "--card-foreground": "#ABB2BF",
      "--popover": "#2C323C",
      "--popover-foreground": "#ABB2BF",
      "--primary": "#61AFEF",
      "--primary-foreground": "#282C34",
      "--secondary": "#2C323C",
      "--secondary-foreground": "#ABB2BF",
      "--muted": "#2C313C",
      "--muted-foreground": "#5C6370",
      "--accent": "#3E4451",
      "--accent-foreground": "#ABB2BF",
      "--destructive": "#E06C75",
      "--destructive-foreground": "#282C34",
      "--border": "#3E4451",
      "--input": "#3E4451",
      "--ring": "#61AFEF",
      "--radius": "0.625rem",
      "--sidebar": "#21252B",
      "--sidebar-foreground": "#ABB2BF",
      "--sidebar-accent": "#2C313C",
      "--sidebar-accent-foreground": "#ABB2BF",
      "--sidebar-border": "#3E4451",
      "--brand": "#61AFEF",
      "--brand-foreground": "#282C34",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    type: "dark",
    colors: {
      "--background": "#282A36",
      "--foreground": "#F8F8F2",
      "--card": "#2D2F3E",
      "--card-foreground": "#F8F8F2",
      "--popover": "#2D2F3E",
      "--popover-foreground": "#F8F8F2",
      "--primary": "#BD93F9",
      "--primary-foreground": "#282A36",
      "--secondary": "#2D2F3E",
      "--secondary-foreground": "#F8F8F2",
      "--muted": "#44475A",
      "--muted-foreground": "#6272A4",
      "--accent": "#44475A",
      "--accent-foreground": "#F8F8F2",
      "--destructive": "#FF5555",
      "--destructive-foreground": "#F8F8F2",
      "--border": "#44475A",
      "--input": "#44475A",
      "--ring": "#BD93F9",
      "--radius": "0.625rem",
      "--sidebar": "#21222C",
      "--sidebar-foreground": "#F8F8F2",
      "--sidebar-accent": "#44475A",
      "--sidebar-accent-foreground": "#F8F8F2",
      "--sidebar-border": "#44475A",
      "--brand": "#BD93F9",
      "--brand-foreground": "#282A36",
    },
  },
  {
    id: "matrix",
    label: "Matrix",
    type: "dark",
    colors: {
      "--background": "#0D0D0D",
      "--foreground": "#00FF41",
      "--card": "#111111",
      "--card-foreground": "#00FF41",
      "--popover": "#111111",
      "--popover-foreground": "#00FF41",
      "--primary": "#00FF41",
      "--primary-foreground": "#0D0D0D",
      "--secondary": "#111111",
      "--secondary-foreground": "#00FF41",
      "--muted": "#1A1A1A",
      "--muted-foreground": "#008751",
      "--accent": "#003300",
      "--accent-foreground": "#00FF41",
      "--destructive": "#FF0041",
      "--destructive-foreground": "#0D0D0D",
      "--border": "#003300",
      "--input": "#003300",
      "--ring": "#00FF41",
      "--radius": "0.625rem",
      "--sidebar": "#080808",
      "--sidebar-foreground": "#00AA22",
      "--sidebar-accent": "#001100",
      "--sidebar-accent-foreground": "#00FF41",
      "--sidebar-border": "#003300",
      "--brand": "#00FF41",
      "--brand-foreground": "#0D0D0D",
    },
  },
  {
    id: "github-dark",
    label: "GitHub Dark",
    type: "dark",
    colors: {
      "--background": "#0D1117",
      "--foreground": "#C9D1D9",
      "--card": "#161B22",
      "--card-foreground": "#C9D1D9",
      "--popover": "#161B22",
      "--popover-foreground": "#C9D1D9",
      "--primary": "#58A6FF",
      "--primary-foreground": "#0D1117",
      "--secondary": "#161B22",
      "--secondary-foreground": "#C9D1D9",
      "--muted": "#21262D",
      "--muted-foreground": "#8B949E",
      "--accent": "#21262D",
      "--accent-foreground": "#C9D1D9",
      "--destructive": "#F85149",
      "--destructive-foreground": "#0D1117",
      "--border": "#30363D",
      "--input": "#30363D",
      "--ring": "#58A6FF",
      "--radius": "0.625rem",
      "--sidebar": "#0A0E14",
      "--sidebar-foreground": "#C9D1D9",
      "--sidebar-accent": "#161B22",
      "--sidebar-accent-foreground": "#C9D1D9",
      "--sidebar-border": "#21262D",
      "--brand": "#58A6FF",
      "--brand-foreground": "#0D1117",
    },
  },
  {
    id: "monokai",
    label: "Monokai",
    type: "dark",
    colors: {
      "--background": "#272822",
      "--foreground": "#F8F8F2",
      "--card": "#2D2E27",
      "--card-foreground": "#F8F8F2",
      "--popover": "#2D2E27",
      "--popover-foreground": "#F8F8F2",
      "--primary": "#A6E22E",
      "--primary-foreground": "#272822",
      "--secondary": "#2D2E27",
      "--secondary-foreground": "#F8F8F2",
      "--muted": "#3E3D32",
      "--muted-foreground": "#75715E",
      "--accent": "#3E3D32",
      "--accent-foreground": "#F8F8F2",
      "--destructive": "#F92672",
      "--destructive-foreground": "#272822",
      "--border": "#3E3D32",
      "--input": "#3E3D32",
      "--ring": "#A6E22E",
      "--radius": "0.625rem",
      "--sidebar": "#1E1F1C",
      "--sidebar-foreground": "#F8F8F2",
      "--sidebar-accent": "#3E3D32",
      "--sidebar-accent-foreground": "#F8F8F2",
      "--sidebar-border": "#3E3D32",
      "--brand": "#A6E22E",
      "--brand-foreground": "#272822",
    },
  },
  {
    id: "vs-dark",
    label: "VS Dark",
    type: "dark",
    colors: {
      "--background": "#1E1E1E",
      "--foreground": "#D4D4D4",
      "--card": "#252526",
      "--card-foreground": "#D4D4D4",
      "--popover": "#252526",
      "--popover-foreground": "#D4D4D4",
      "--primary": "#569CD6",
      "--primary-foreground": "#1E1E1E",
      "--secondary": "#252526",
      "--secondary-foreground": "#D4D4D4",
      "--muted": "#2D2D2D",
      "--muted-foreground": "#6A6A6A",
      "--accent": "#2D2D2D",
      "--accent-foreground": "#D4D4D4",
      "--destructive": "#F44747",
      "--destructive-foreground": "#1E1E1E",
      "--border": "#3C3C3C",
      "--input": "#3C3C3C",
      "--ring": "#569CD6",
      "--radius": "0.625rem",
      "--sidebar": "#252526",
      "--sidebar-foreground": "#D4D4D4",
      "--sidebar-accent": "#2D2D2D",
      "--sidebar-accent-foreground": "#D4D4D4",
      "--sidebar-border": "#3C3C3C",
      "--brand": "#569CD6",
      "--brand-foreground": "#1E1E1E",
    },
  },
  {
    id: "github-light",
    label: "GitHub Light",
    type: "light",
    colors: {
      "--background": "#FFFFFF",
      "--foreground": "#1F2328",
      "--card": "#F6F8FA",
      "--card-foreground": "#1F2328",
      "--popover": "#F6F8FA",
      "--popover-foreground": "#1F2328",
      "--primary": "#0969DA",
      "--primary-foreground": "#FFFFFF",
      "--secondary": "#F6F8FA",
      "--secondary-foreground": "#1F2328",
      "--muted": "#F6F8FA",
      "--muted-foreground": "#656D76",
      "--accent": "#D0D7DE",
      "--accent-foreground": "#1F2328",
      "--destructive": "#CF222E",
      "--destructive-foreground": "#FFFFFF",
      "--border": "#D0D7DE",
      "--input": "#D0D7DE",
      "--ring": "#0969DA",
      "--radius": "0.625rem",
      "--sidebar": "#F6F8FA",
      "--sidebar-foreground": "#1F2328",
      "--sidebar-accent": "#E8ECF0",
      "--sidebar-accent-foreground": "#1F2328",
      "--sidebar-border": "#D0D7DE",
      "--brand": "#0969DA",
      "--brand-foreground": "#FFFFFF",
    },
  },
];

export const DEFAULT_APP_THEME = "one-dark-pro";

export function getAppTheme(id: string): AppTheme {
  return APP_THEMES.find((t) => t.id === id) ?? APP_THEMES[0];
}
